import {
  StateGraph,
  StateSchema,
  START,
  END,
  type GraphNode,
  type CompiledStateGraph,
} from "@langchain/langgraph";
import z from "zod";
import { models } from "./model.ai";
import { createAgent, HumanMessage, toolStrategy } from "langchain";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    winner: z.enum(["solution_1", "solution_2", "tie"]).default("tie"),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof State> = async (state) => {
  const mistralModel = models.mistral;
  const cohereModel = models.cohere;

  if (!mistralModel || !cohereModel) {
    throw new Error(
      "Mistral and Cohere models must be configured to run solutionNode.",
    );
  }

  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  };
};

const judgeNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  const judge = createAgent({
    model: models.mistral!,
    responseFormat: toolStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores. and present the winner. The problem is: ${problem}. The first solution is: ${solution_1}. The second solution is: ${solution_2}.`,
  });
  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
    Problem: ${problem}
    Solution_1: ${solution_1}
    Solution_2: ${solution_2}
  `),
    ],
  });
  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,    
  } = judgeResponse.structuredResponse;

  const winner =
    solution_1_score === solution_2_score
      ? "tie"
      : solution_1_score > solution_2_score
        ? "solution_1"
        : "solution_2";

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      winner,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};
const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("judgeNode", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judgeNode")
  .addEdge("judgeNode", END)
  .compile();

export default async function (problem: string) { 
    if (!problem?.trim()) {
        throw new Error("problem is required and must be a non-empty string");
    }

    const result = await graph.invoke({
        problem: problem
    })

    return result

}
